ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "FK_PRENOTAZIONI_UTENTE" FOREIGN KEY ("ID_UTENTE") REFERENCES "UTENTI" ("ID_UTENTE");
ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "CHECK_TIPO_PRENOTAZIONE" CHECK ("TIPO_PRENOTAZIONE" IN (1, 2));
ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "CHECK_NUMERO_ADULTI" CHECK ("NUMERO_ADULTI" BETWEEN 1 AND 9);
ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "CHECK_NUMERO_BAMBINI" CHECK ("NUMERO_BAMBINI" BETWEEN 0 AND 8);
ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "CHECK_NUMERO_NEONATI" CHECK ("NUMERO_NEONATI" BETWEEN 0 AND 1);
ALTER TABLE "PRENOTAZIONI" ADD CONSTRAINT "CHK_TOTAL_ADULTI_BAMBINI" CHECK ("NUMERO_ADULTI" + "NUMERO_BAMBINI" <= 9); COMMIT;
