CREATE OR REPLACE TRIGGER TRG_CALCOLA_COSTO_E_CODICE
BEFORE INSERT ON PRENOTAZIONI
FOR EACH ROW
DECLARE
    PREZZO_ANDATA NUMBER;
    PREZZO_RITORNO NUMBER;
BEGIN
    :NEW.CODICE_PRENOTAZIONE := SUBSTR(DBMS_RANDOM.STRING('U', 8), 1, 8);

    SELECT PREZZO INTO PREZZO_ANDATA
    FROM VOLI
    WHERE CODICE_VOLO = :NEW.CODICE_VOLO_ANDATA;

    IF :NEW.TIPO_PRENOTAZIONE = 2 THEN
        SELECT PREZZO INTO PREZZO_RITORNO
        FROM VOLI
        WHERE CODICE_VOLO = :NEW.CODICE_VOLO_RITORNO;
    ELSE
        PREZZO_RITORNO := 0;
    END IF;

    :NEW.COSTO := 
        (PREZZO_ANDATA + PREZZO_RITORNO) *
        (:NEW.NUMERO_ADULTI + 
        (:NEW.NUMERO_BAMBINI * 0.75) + 
        (:NEW.NUMERO_NEONATI * 0.10));
END; COMMIT;
