CREATE VIEW V_UTENTI AS
SELECT U.NOME, U.COGNOME, U.EMAIL, S.TIPO AS SESSO, U.DATA_DI_NASCITA, T.TIPO AS TIPOLOGIA_TELEFONO, P.TIPO AS PREFISSO, U.NUMERO_TELEFONO ,
I.TIPO AS TIPOLOGIA_INDIRIZZO, U.INDIRIZZO, U.CAP, U.CITTA, U.PROVINCIA, U.NAZIONE
FROM UTENTI U
JOIN SESSO S ON U.SESSO = S.ID
JOIN TIPOLOGIA_TELEFONO T ON U.TIPOLOGIA_TELEFONO = T.ID
JOIN PREFISSO P ON U.PREFISSO = P.ID
JOIN TIPOLOGIA_INDIRIZZO I ON U.TIPOLOGIA_INDIRIZZO = I.ID;
