CREATE INDEX IDX_PRENOTAZIONI_ID_UTENTE
ON PRENOTAZIONI (ID_UTENTE);

CREATE INDEX IDX_PRENOTAZIONI_CODICE_VOLO_ANDATA 
ON PRENOTAZIONI (CODICE_VOLO_ANDATA);

CREATE INDEX IDX_PRENOTAZIONI_CODICE_VOLO_RITORNO 
ON PRENOTAZIONI (CODICE_VOLO_RITORNO); COMMIT;
