CREATE OR REPLACE TRIGGER TRG_INSERT_FEDELTA
AFTER INSERT ON UTENTI
FOR EACH ROW
BEGIN
    INSERT INTO FEDELTA (EMAIL, CODICE_FEDELTA)
    VALUES (
        :NEW.EMAIL,
        SUBSTR(DBMS_RANDOM.STRING('U', 10), 1, 10)
    );
END; COMMIT;
