CREATE OR REPLACE TRIGGER VERIFICA_E_AGGIORNA_POSTI
BEFORE INSERT ON PRENOTAZIONI
FOR EACH ROW
DECLARE
    V_NUMERO_POSTI_TOTALE NUMBER;
    V_POSTI_DISPONIBILI_ANDATA NUMBER;
    V_POSTI_DISPONIBILI_RITORNO NUMBER;
BEGIN
    V_NUMERO_POSTI_TOTALE := :NEW.NUMERO_ADULTI + :NEW.NUMERO_BAMBINI + :NEW.NUMERO_NEONATI;

    SELECT COUNT(*)
    INTO V_POSTI_DISPONIBILI_ANDATA
    FROM POSTI
    WHERE CODICE_VOLO = :NEW.CODICE_VOLO_ANDATA
    AND STATO = 'DISPONIBILE'
    AND NUMERO_POSTO IN (SELECT TO_NUMBER(REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_ANDATA, '[^ -]+', 1, LEVEL))
                         FROM DUAL
                         CONNECT BY REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_ANDATA, '[^ -]+', 1, LEVEL) IS NOT NULL);

    IF V_POSTI_DISPONIBILI_ANDATA <> V_NUMERO_POSTI_TOTALE THEN
        RAISE_APPLICATION_ERROR(-20001, 'NON TUTTI I POSTI SCELTI SONO DISPONIBILI PER IL VOLO DI ANDATA.');
    END IF;

    IF :NEW.TIPO_PRENOTAZIONE = '2' THEN
        SELECT COUNT(*)
        INTO V_POSTI_DISPONIBILI_RITORNO
        FROM POSTI
        WHERE CODICE_VOLO = :NEW.CODICE_VOLO_RITORNO
        AND STATO = 'DISPONIBILE'
        AND NUMERO_POSTO IN (SELECT TO_NUMBER(REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_RITORNO, '[^ -]+', 1, LEVEL))
                             FROM DUAL
                             CONNECT BY REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_RITORNO, '[^ -]+', 1, LEVEL) IS NOT NULL);
    END IF;

    FOR I IN (SELECT TO_NUMBER(REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_ANDATA, '[^ -]+', 1, LEVEL)) AS NUMERO_POSTO
              FROM DUAL
              CONNECT BY REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_ANDATA, '[^ -]+', 1, LEVEL) IS NOT NULL) LOOP
        UPDATE POSTI
        SET STATO = 'OCCUPATO'
        WHERE CODICE_VOLO = :NEW.CODICE_VOLO_ANDATA
        AND NUMERO_POSTO = I.NUMERO_POSTO;
    END LOOP;

    IF :NEW.TIPO_PRENOTAZIONE = '2' THEN
        FOR I IN (SELECT TO_NUMBER(REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_RITORNO, '[^ -]+', 1, LEVEL)) AS NUMERO_POSTO
                  FROM DUAL
                  CONNECT BY REGEXP_SUBSTR(:NEW.POSTI_ACQUISTATI_RITORNO, '[^ -]+', 1, LEVEL) IS NOT NULL) LOOP
            UPDATE POSTI
            SET STATO = 'OCCUPATO'
            WHERE CODICE_VOLO = :NEW.CODICE_VOLO_RITORNO
            AND NUMERO_POSTO = I.NUMERO_POSTO;
        END LOOP;
    END IF;

END;
