BEGIN
    FOR CODICE_VOLO IN (SELECT CODICE_VOLO FROM VOLI) LOOP
        FOR i IN 1..100 LOOP
            INSERT INTO POSTI (CODICE_VOLO, NUMERO_POSTO, STATO)
            VALUES (CODICE_VOLO.CODICE_VOLO, i, 'DISPONIBILE');
        END LOOP;
    END LOOP;
END;
