INSERT INTO TIPOLOGIA_TELEFONO VALUES ('1','Telefono aziendale');
INSERT INTO TIPOLOGIA_TELEFONO VALUES ('2','Telefono di casa');
INSERT INTO TIPOLOGIA_TELEFONO VALUES ('3','Cellulare aziendale');
INSERT INTO TIPOLOGIA_TELEFONO VALUES ('4','Cellulare di casa'); COMMIT;
